server:
  port: 8001

spring:
  application:
    name: common-service
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.tktnwuhbmofbvroawxae
    password: "!Q@W#E$R%T6y"
#    url: jdbc:postgresql://localhost:5432/ast
#    username: postgres
#    password: postgres

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.api.ast
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
